In [2]:
import numpy as np

In [4]:
a = np.arange(0,27,3).reshape(3,3)
a

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [14]:
a / np.linalg.norm(a, axis=1)[:, np.newaxis]

array([[0.        , 0.4472136 , 0.89442719],
       [0.42426407, 0.56568542, 0.70710678],
       [0.49153915, 0.57346234, 0.65538554]])

In [15]:
a

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [18]:
np.max(a, axis=0)

array([18, 21, 24])

In [19]:
np.argmax(a, axis=0)

array([2, 2, 2])